// Code generated by hertz generator.

package Task

import (
	"github.com/cloudwego/hertz/pkg/app"
	"hertz-mylist/biz/router/middleware"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _taskMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{middleware.HzJwtMw.MiddlewareFunc()}
}

func _createtaskMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatetaskMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deleteMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletetaskMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getdetailMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _gettaskdetailMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getlistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _pagesizeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _gettasklistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateMw() []app.HandlerFunc {
	// your code...
	return nil
}
